apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus
    url: http://prometheus:9090
    access: proxy
    isDefault: true
    editable: false
    jsonData:
      timeInterval: 15s

  - name: Jaeger
    type: jaeger
    uid: jaeger
    url: http://jaeger:16686
    access: proxy
    editable: false
    jsonData:
      tracesToLogsV2:
        datasourceUid: elasticsearch
        spanStartTimeShift: -1m
        spanEndTimeShift: 1m
        filterByTraceID: true

  - name: Elasticsearch
    type: elasticsearch
    uid: elasticsearch
    url: http://elasticsearch:9200
    access: proxy
    editable: false
    jsonData:
      index: vartrack-logs
      timeField: "@timestamp"
      esVersion: "8.0.0"
      logMessageField: message
      logLevelField: level
